replicaCount: 1

image:
  repository: elementor-rnm-api
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 5000

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  className: nginx
  host: myapi.local
  path: /

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: true
  path: /healthcheck
  port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /healthcheck
  port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10

hpa:
  enabled: false        # ב-KIND אין metrics-server, השאר false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50





