name: Deploy to KIND using Helm

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create KIND cluster (name=kind)
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: kind

      - name: Build Docker image (local tag for KIND)
        run: |
          docker build -t elementor-rnm-api:latest .

      - name: Load image into KIND
        run: |
          kind load docker-image --name kind elementor-rnm-api:latest

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy with Helm (override image to local)
        run: |
          helm upgrade --install elementor-rnm-api ./helm \
            --set image.repository=elementor-rnm-api \
            --set image.tag=latest

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/elementor-rnm-api --timeout=180s
          kubectl get pods -o wide
          kubectl get svc -o wide

      - name: Smoke test (healthcheck or root)
        run: |
          kubectl run curl --image=curlimages/curl:8.10.1 --restart=Never --rm -i -- \
            sh -c "curl -sf http://elementor-rnm-api/healthcheck || curl -sf http://elementor-rnm-api/"


